/** @fileoverview Default data and constants for the English Learning App */

export const STORAGE_KEYS = {
  VOCAB: 'eng-vocab-store',
  NOTES: 'eng-notes-store',
  SETTINGS: 'eng-settings-store',
}

export const CATEGORIES = {
  all: 'All',
  general: 'General IT',
  iot: 'IoT / Embedded',
}

export const SRS_INTERVALS = [1, 3, 7, 14, 30, 60, 90]

const now = Date.now()
const day = 86400000

/** 150+ vocabulary items pre-loaded into the app */
export const VOCABULARY = [
  // ── General IT ──────────────────────────────────────────────────────────────
  { id: 1, term: 'Algorithm', meaning: 'A step-by-step procedure for solving a problem or accomplishing a task', example: 'A sorting algorithm arranges elements in order.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 2, term: 'API', meaning: 'Application Programming Interface — a set of rules that allows programs to communicate', example: 'We use the REST API to fetch user data from the server.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 3, term: 'Database', meaning: 'An organized collection of structured information stored electronically', example: 'We store user profiles in a PostgreSQL database.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 4, term: 'Framework', meaning: 'A foundational structure providing pre-built components and conventions for development', example: 'React is a JavaScript framework for building UIs.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 5, term: 'Debug', meaning: 'The process of finding and fixing errors or bugs in code', example: 'I spent two hours debugging the null pointer exception.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 6, term: 'Abstraction', meaning: 'Hiding complex implementation details behind a simpler interface', example: 'A car driver uses the steering wheel without knowing engine internals — that is abstraction.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 7, term: 'Agile', meaning: 'An iterative software development methodology emphasizing flexibility and collaboration', example: 'Our team follows Agile with two-week sprints.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 8, term: 'Authentication', meaning: 'The process of verifying the identity of a user or system', example: 'Login with username and password is a form of authentication.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 9, term: 'Authorization', meaning: 'Determining what actions or resources a verified user is allowed to access', example: 'Only admins are authorized to delete records.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 10, term: 'Backend', meaning: 'Server-side code and infrastructure that handles data processing and business logic', example: 'Node.js powers the backend API of our application.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 11, term: 'Bandwidth', meaning: 'The maximum rate at which data can be transferred over a network', example: 'Streaming 4K video requires high bandwidth.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 12, term: 'Binary', meaning: 'A base-2 number system using only digits 0 and 1, fundamental to computing', example: 'The number 5 in binary is 101.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 13, term: 'Boolean', meaning: 'A data type with only two possible values: true or false', example: 'isLoggedIn is a boolean variable.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 14, term: 'Cache', meaning: 'Temporary high-speed storage for frequently accessed data to improve performance', example: 'We cache API responses to reduce server load.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 15, term: 'CLI', meaning: 'Command Line Interface — a text-based interface for interacting with a computer', example: 'Use the CLI to run git commands.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 16, term: 'Compiler', meaning: 'A program that translates source code into machine code before execution', example: 'GCC compiles C code into an executable binary.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 17, term: 'Concurrency', meaning: 'Multiple tasks executing in overlapping time periods, sharing resources', example: 'Concurrency allows a web server to handle multiple requests simultaneously.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 18, term: 'Deployment', meaning: 'The process of releasing and installing software into a production environment', example: 'We deploy to AWS every Friday after testing.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 19, term: 'Docker', meaning: 'A platform for packaging applications into isolated containers with their dependencies', example: 'Docker ensures the app runs the same on every machine.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 20, term: 'Encryption', meaning: 'Converting data into an unreadable format to protect it from unauthorized access', example: 'HTTPS uses TLS encryption to protect data in transit.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 21, term: 'Git', meaning: 'A distributed version control system for tracking changes in source code', example: 'Use git commit to save your changes locally.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 22, term: 'HTTP', meaning: 'HyperText Transfer Protocol — the foundation of data communication on the web', example: 'The browser sends an HTTP GET request to fetch a webpage.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 23, term: 'IDE', meaning: 'Integrated Development Environment — software combining code editor, debugger, and build tools', example: 'VS Code is a popular IDE for web development.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 24, term: 'JSON', meaning: 'JavaScript Object Notation — a lightweight, human-readable data interchange format', example: 'APIs often return data as JSON: {"name": "Alice", "age": 30}', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 25, term: 'Kubernetes', meaning: 'An open-source container orchestration platform for automating deployment and scaling', example: 'Kubernetes manages our microservices cluster in production.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 26, term: 'Latency', meaning: 'The delay between a request being made and the response being received', example: 'High latency causes lag in online gaming.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 27, term: 'Library', meaning: 'A collection of pre-written reusable code modules for common tasks', example: 'Lodash is a utility library with helpful functions.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 28, term: 'Memory Leak', meaning: 'A bug where a program fails to release memory it no longer needs, causing gradual resource exhaustion', example: 'The memory leak caused the app to crash after running for 24 hours.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 29, term: 'Middleware', meaning: 'Software that connects different systems or acts as intermediary between components', example: 'Express middleware handles authentication before routing.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 30, term: 'Module', meaning: 'A self-contained unit of code with a specific purpose that can be imported and reused', example: 'Each feature is in its own module for maintainability.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 31, term: 'REST', meaning: 'Representational State Transfer — an architectural style for designing networked APIs', example: 'GET /users/1 is a RESTful endpoint to fetch user with id 1.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 32, term: 'Runtime', meaning: 'The period when a program is executing; also the environment that executes the code', example: 'Node.js is a JavaScript runtime built on Chrome\'s V8 engine.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 33, term: 'SDK', meaning: 'Software Development Kit — a set of tools and libraries for building applications on a platform', example: 'We use the AWS SDK to interact with S3 buckets.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 34, term: 'SQL', meaning: 'Structured Query Language — a language for managing and querying relational databases', example: 'SELECT * FROM users WHERE active = true; is a SQL query.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 35, term: 'SSL/TLS', meaning: 'Security protocols providing encrypted communication over a network', example: 'Websites with HTTPS use SSL/TLS certificates.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 36, term: 'Thread', meaning: 'The smallest unit of execution within a process, enabling parallel operations', example: 'A multi-threaded server handles each request in a separate thread.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 37, term: 'Token', meaning: 'A string credential (often JWT) used for authenticating API requests', example: 'Include the Bearer token in the Authorization header.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 38, term: 'Version Control', meaning: 'A system for tracking and managing changes to files over time', example: 'Git is the most widely used version control system.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 39, term: 'Webhook', meaning: 'An HTTP callback that notifies your app when a specific event occurs in another system', example: 'GitHub sends a webhook to our CI server when code is pushed.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 40, term: 'Recursion', meaning: 'A programming technique where a function calls itself to solve smaller subproblems', example: 'Factorial of n = n * factorial(n-1) is a classic recursion example.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 41, term: 'Inheritance', meaning: 'An OOP concept where a class derives properties and methods from a parent class', example: 'Dog extends Animal, inheriting the breathe() method.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 42, term: 'Polymorphism', meaning: 'The ability for objects of different types to be treated as instances of a common interface', example: 'A draw() method works differently for Circle and Square objects.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 43, term: 'Encapsulation', meaning: 'Bundling data and methods together and restricting direct access to internal state', example: 'Private class fields are a form of encapsulation.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 44, term: 'Microservice', meaning: 'A small, independently deployable service focused on a single business function', example: 'Our app has separate microservices for auth, payments, and notifications.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 45, term: 'GraphQL', meaning: 'A query language for APIs that allows clients to request exactly the data they need', example: 'With GraphQL, you can fetch user name and email in one query.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 46, term: 'WebSocket', meaning: 'A protocol providing full-duplex communication channels over a single TCP connection', example: 'Chat applications use WebSockets for real-time messaging.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 47, term: 'CDN', meaning: 'Content Delivery Network — distributed servers delivering content from locations near users', example: 'Cloudflare CDN reduces latency by caching assets globally.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 48, term: 'DNS', meaning: 'Domain Name System — translates human-readable domain names to IP addresses', example: 'DNS resolves "google.com" to 142.250.64.14.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 49, term: 'Load Balancer', meaning: 'A device that distributes incoming traffic across multiple servers to ensure reliability', example: 'The load balancer routes requests to the least-busy server.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 50, term: 'CI/CD', meaning: 'Continuous Integration and Continuous Delivery — automating testing and deployment pipelines', example: 'Our CI/CD pipeline runs tests and deploys on every merge to main.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 51, term: 'Containerization', meaning: 'Packaging an application with all its dependencies into a portable, isolated unit', example: 'Docker containerization ensures consistent environments across dev and prod.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 52, term: 'Scalability', meaning: 'The ability of a system to handle increased workload by adding resources', example: 'Horizontal scalability adds more servers as traffic grows.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 53, term: 'Refactoring', meaning: 'Restructuring existing code to improve readability and maintainability without changing behavior', example: 'We refactored the payment module to reduce code duplication.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 54, term: 'Unit Test', meaning: 'A test that validates a single function or component in isolation from the rest of the system', example: 'We write unit tests for each utility function using Jest.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 55, term: 'Dependency Injection', meaning: 'Providing dependencies to a class from the outside rather than creating them internally', example: 'Injecting a database connection into a service enables easier testing.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 56, term: 'Design Pattern', meaning: 'A reusable solution template for a commonly occurring software design problem', example: 'The Observer pattern is used in event-driven systems.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 57, term: 'MVC', meaning: 'Model-View-Controller — an architectural pattern separating data, UI, and control logic', example: 'Rails and Django follow the MVC pattern.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 58, term: 'CORS', meaning: 'Cross-Origin Resource Sharing — a browser security mechanism controlling cross-domain requests', example: 'Add CORS headers to allow your frontend to call the API.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 59, term: 'OAuth', meaning: 'An open standard protocol for secure access delegation without sharing passwords', example: '"Login with Google" uses OAuth 2.0.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 60, term: 'JWT', meaning: 'JSON Web Token — a compact, URL-safe token for transmitting authentication claims', example: 'The server issues a JWT after login; the client sends it with each request.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 61, term: 'Hash Function', meaning: 'A function that maps input data of any size to a fixed-size output value', example: 'bcrypt is a hash function used to store passwords securely.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 62, term: 'Queue', meaning: 'A FIFO data structure where elements are added at the back and removed from the front', example: 'A print queue processes jobs in the order they arrive.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 63, term: 'Stack (DS)', meaning: 'A LIFO data structure where the last element added is the first to be removed', example: 'Function calls use a call stack to track execution context.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 64, term: 'HashMap', meaning: 'A key-value data structure providing O(1) average lookup, insert, and delete operations', example: 'Use a HashMap to count word frequencies in O(n) time.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 65, term: 'Regex', meaning: 'Regular Expression — a pattern for matching, searching, and manipulating strings', example: '/^[a-z0-9]+@[a-z]+\\.com$/ is a regex for validating email.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 66, term: 'Promise', meaning: 'A JavaScript object representing the eventual completion or failure of an asynchronous operation', example: 'fetch() returns a Promise that resolves with the response.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 67, term: 'Async/Await', meaning: 'Syntactic sugar over Promises that makes asynchronous code look synchronous', example: 'const data = await fetch(url).then(r => r.json());', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 68, term: 'Big O Notation', meaning: 'A mathematical notation describing how algorithm performance scales with input size', example: 'Binary search runs in O(log n) time.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 69, term: 'Garbage Collection', meaning: 'Automatic memory management that frees memory no longer referenced by the program', example: 'JavaScript uses garbage collection to manage heap memory.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 70, term: 'Deadlock', meaning: 'A state where two or more threads are blocked forever, each waiting for the other to release a resource', example: 'Thread A holds lock 1 and waits for lock 2; Thread B holds lock 2 and waits for lock 1.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 71, term: 'Race Condition', meaning: 'A bug where the outcome depends on the unpredictable timing of multiple threads accessing shared data', example: 'Two threads reading and incrementing a counter without a lock causes a race condition.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 72, term: 'TCP/IP', meaning: 'The foundational protocol suite for internet communication providing reliable data delivery', example: 'HTTP runs over TCP/IP to ensure packets arrive in order.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 73, term: 'UDP', meaning: 'User Datagram Protocol — a connectionless transport protocol that prioritizes speed over reliability', example: 'Video streaming uses UDP to minimize latency despite some packet loss.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 74, term: 'SSH', meaning: 'Secure Shell — a cryptographic protocol for secure remote login and command execution', example: 'ssh user@server.com connects securely to a remote machine.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 75, term: 'DevOps', meaning: 'A set of practices combining software development and IT operations for faster delivery', example: 'DevOps teams use CI/CD pipelines to ship features daily.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 76, term: 'Singleton', meaning: 'A design pattern ensuring a class has only one instance throughout the application', example: 'A database connection pool is often implemented as a singleton.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 77, term: 'Proxy', meaning: 'An intermediary server or object that intercepts requests to another resource', example: 'A reverse proxy like Nginx forwards requests to backend services.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 78, term: 'Repository', meaning: 'A storage location for source code, packages, or data with history tracking', example: 'The project repository is hosted on GitHub.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 79, term: 'Event Loop', meaning: 'A mechanism that handles asynchronous callbacks in single-threaded environments like JavaScript', example: 'The event loop allows Node.js to handle thousands of connections concurrently.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 80, term: 'Monolith', meaning: 'A single, unified application where all components are tightly coupled and deployed together', example: 'Our legacy app is a monolith — we are migrating it to microservices.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 81, term: 'Cloud Computing', meaning: 'Delivering computing services like storage, servers, and software over the internet on demand', example: 'AWS and Azure are the leading cloud computing platforms.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 82, term: 'Virtualization', meaning: 'Creating virtual versions of hardware resources to run multiple OS instances on one machine', example: 'VMware provides virtualization for running multiple virtual machines.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 83, term: 'Linked List', meaning: 'A linear data structure where each node contains data and a pointer to the next node', example: 'Inserting at the head of a linked list is O(1).', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 84, term: 'Binary Tree', meaning: 'A tree data structure where each node has at most two children: left and right', example: 'A binary search tree allows O(log n) search operations.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 85, term: 'Mutex', meaning: 'A synchronization primitive that prevents multiple threads from accessing a shared resource simultaneously', example: 'Acquire the mutex before reading shared memory to prevent data corruption.', category: 'general', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },

  // ── IoT / Embedded ───────────────────────────────────────────────────────────
  { id: 86, term: 'I2C', meaning: 'Inter-Integrated Circuit — a two-wire serial protocol (SDA + SCL) supporting multiple devices on one bus', example: 'The temperature sensor uses I2C to communicate with the MCU.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 87, term: 'SPI', meaning: 'Serial Peripheral Interface — a four-wire synchronous protocol (MOSI, MISO, SCK, CS) for high-speed communication', example: 'The display module uses SPI for faster data transfer than I2C.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 88, term: 'UART', meaning: 'Universal Asynchronous Receiver-Transmitter — asynchronous serial communication using TX and RX lines', example: 'We use UART to send debug logs from the microcontroller to a PC.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 89, term: 'GPIO', meaning: 'General Purpose Input/Output — digital pins on a microcontroller that can be configured as input or output', example: 'Toggle the LED by writing HIGH to a GPIO pin.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 90, term: 'MCU', meaning: 'Microcontroller Unit — a single integrated circuit containing a CPU, memory, and programmable I/O peripherals', example: 'The STM32 MCU runs the motor control firmware.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 91, term: 'ADC', meaning: 'Analog-to-Digital Converter — converts continuous analog signals to discrete digital values', example: 'Read the analog temperature sensor through the ADC at 12-bit resolution.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 92, term: 'DAC', meaning: 'Digital-to-Analog Converter — converts discrete digital values back to continuous analog signals', example: 'Use the DAC to output a sine wave for the audio amplifier.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 93, term: 'DMA', meaning: 'Direct Memory Access — allows peripherals to transfer data to/from memory without CPU intervention', example: 'Configure DMA for UART to receive data without interrupting the CPU.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 94, term: 'RTOS', meaning: 'Real-Time Operating System — an OS that guarantees task execution within strict timing constraints', example: 'FreeRTOS schedules tasks with deterministic timing for motor control.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 95, term: 'Watchdog Timer', meaning: 'A hardware timer that resets the system if the software fails to periodically reset it, preventing lockups', example: 'Pet the watchdog every 500ms or the MCU will reset automatically.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 96, term: 'Bootloader', meaning: 'A small program that loads the main application firmware into memory on device startup', example: 'The bootloader checks for OTA updates before launching the main firmware.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 97, term: 'Firmware', meaning: 'Low-level software embedded in hardware devices that controls device-specific functions', example: 'We flashed updated firmware to fix the sensor calibration bug.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 98, term: 'PWM', meaning: 'Pulse Width Modulation — a technique using variable duty cycle pulses to control power to devices', example: 'Use PWM to control LED brightness or motor speed.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 99, term: 'Interrupt', meaning: 'A signal that causes the CPU to pause its current task and execute a specific interrupt handler', example: 'Configure a GPIO interrupt to detect button presses immediately.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 100, term: 'MQTT', meaning: 'Message Queuing Telemetry Transport — a lightweight publish/subscribe messaging protocol for IoT', example: 'The sensor publishes temperature to the MQTT broker every 5 seconds.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 101, term: 'CoAP', meaning: 'Constrained Application Protocol — a RESTful web transfer protocol designed for constrained IoT devices', example: 'CoAP uses UDP to minimize overhead on low-power sensors.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 102, term: 'Zigbee', meaning: 'A low-power, low-data-rate wireless mesh networking protocol for IoT and smart home devices', example: 'Zigbee smart bulbs form a mesh network in the smart home.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 103, term: 'Bluetooth LE', meaning: 'Bluetooth Low Energy — a wireless protocol optimized for battery-powered IoT devices with low data rates', example: 'The fitness tracker uses BLE to sync data to your smartphone.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 104, term: 'LoRaWAN', meaning: 'Long Range Wide Area Network — a protocol for long-range, low-power wireless communication in IoT', example: 'LoRaWAN sensors in smart agriculture transmit data up to 15 km away.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 105, term: 'Edge Computing', meaning: 'Processing data near its source rather than sending it to the cloud, reducing latency and bandwidth', example: 'Edge computing on the factory floor analyzes sensor data in real time.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 106, term: 'OTA Update', meaning: 'Over-The-Air — wirelessly delivering firmware or software updates to deployed devices', example: 'We push OTA updates to fix bugs without physically accessing the devices.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 107, term: 'CAN Bus', meaning: 'Controller Area Network — a robust vehicle/industrial bus for microcontrollers to communicate without a host', example: 'CAN Bus connects ECUs in a car to share sensor and control data.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 108, term: 'Modbus', meaning: 'A serial communication protocol widely used in industrial automation and SCADA systems', example: 'The PLC reads sensor values from the remote I/O over Modbus RTU.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 109, term: 'PLC', meaning: 'Programmable Logic Controller — a ruggedized industrial computer for automating manufacturing processes', example: 'The PLC controls the conveyor belt speed based on sensor inputs.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 110, term: 'Sensor Fusion', meaning: 'Combining data from multiple sensors to produce more accurate and reliable measurements', example: 'Sensor fusion from accelerometer + gyroscope gives stable orientation data.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 111, term: 'Deep Sleep', meaning: 'An ultra-low power state where most MCU peripherals are disabled to extend battery life', example: 'Enter deep sleep between readings to achieve 2-year battery life.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 112, term: 'LwIP', meaning: 'Lightweight IP — a small TCP/IP stack designed for embedded systems with limited resources', example: 'LwIP provides TCP/IP networking on an MCU with 64KB RAM.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 113, term: 'Flash Memory', meaning: 'Non-volatile storage used in embedded systems to persist firmware and data across power cycles', example: 'Store configuration parameters in flash memory so they survive reboot.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 114, term: 'EEPROM', meaning: 'Electrically Erasable Programmable Read-Only Memory — byte-addressable non-volatile memory for small data', example: 'Save calibration offsets to EEPROM so they persist after power-off.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 115, term: 'ISR', meaning: 'Interrupt Service Routine — a function that executes immediately when an interrupt signal is received', example: 'Keep the ISR short and fast; set a flag and handle logic in the main loop.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 116, term: 'Polling', meaning: 'Repeatedly checking a device or flag status in a loop instead of using interrupts', example: 'Polling the UART status register wastes CPU cycles compared to interrupts.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 117, term: 'HAL', meaning: 'Hardware Abstraction Layer — an API providing a uniform interface to hardware, easing portability', example: 'Use HAL_GPIO_WritePin() instead of direct register access for portability.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 118, term: 'JTAG', meaning: 'Joint Test Action Group — a standard interface for debugging and programming embedded systems', example: 'Use a JTAG debugger to step through firmware and inspect registers.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 119, term: 'Volatile Keyword', meaning: 'A C/C++ qualifier telling the compiler not to optimize accesses to a variable that can change externally', example: 'Declare ISR-updated flags as volatile to prevent compiler optimization.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 120, term: 'Endianness', meaning: 'The byte ordering convention used to store multi-byte values: big-endian (MSB first) or little-endian (LSB first)', example: 'Convert between network (big-endian) and host byte order with htons().', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 121, term: 'CRC', meaning: 'Cyclic Redundancy Check — an error-detecting code used to verify data integrity in communications', example: 'Append a CRC32 checksum to each data packet to detect transmission errors.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 122, term: 'Semaphore', meaning: 'An RTOS synchronization primitive used to signal between tasks or limit resource access', example: 'Use a binary semaphore to signal when new sensor data is ready.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 123, term: 'Message Queue', meaning: 'An RTOS mechanism for passing data safely between tasks using a buffered FIFO structure', example: 'Send sensor readings via message queue to the processing task.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 124, term: 'Memory Map', meaning: 'A layout describing how memory regions (flash, RAM, peripherals) are addressed in an embedded system', example: 'Refer to the datasheet memory map to find the GPIO base address.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 125, term: 'Cross-compilation', meaning: 'Compiling code on one architecture (host) to run on a different target architecture', example: 'Cross-compile for ARM Cortex-M4 using the arm-none-eabi-gcc toolchain.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 126, term: 'Device Tree', meaning: 'A data structure describing hardware topology in embedded Linux systems to decouple board support from kernel', example: 'Enable the I2C peripheral in the device tree overlay.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 127, term: 'NFC', meaning: 'Near Field Communication — a short-range wireless protocol for data exchange within 4 cm', example: 'Tap your phone to the NFC tag to configure the IoT device.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 128, term: 'Matter Protocol', meaning: 'A smart home interoperability standard allowing devices from different vendors to work together', example: 'The new smart plug supports Matter, so it works with Alexa, Google, and Apple.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 129, term: 'Power Management', meaning: 'Techniques to minimize energy consumption in embedded and IoT devices to extend battery life', example: 'Implement power management by shutting off unused peripherals during idle.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 130, term: 'Register (HW)', meaning: 'A small, fast storage location inside a processor or peripheral used to control hardware behavior', example: 'Write to the control register to configure the timer peripheral.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 131, term: 'BSP', meaning: 'Board Support Package — a layer of software providing drivers and configuration for a specific hardware board', example: 'The BSP initializes clocks and pinmux before the application starts.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 132, term: 'Task Priority', meaning: 'A value assigned to RTOS tasks determining scheduling order when multiple tasks are ready to run', example: 'Assign higher priority to the motor control task than the logging task.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 133, term: 'Linker Script', meaning: 'A configuration file controlling how the linker places code and data sections in memory', example: 'The linker script maps .text to flash and .data to RAM.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 134, term: 'Tick Rate', meaning: 'The frequency at which an RTOS timer interrupt fires, determining the minimum task scheduling resolution', example: 'A 1000 Hz tick rate gives 1 ms scheduling resolution in FreeRTOS.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 135, term: 'Wi-Fi', meaning: 'A wireless networking technology using radio waves to provide high-speed internet access', example: 'The ESP32 connects to Wi-Fi to upload sensor data to the cloud.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 136, term: 'Thread Safety', meaning: 'Property of code that functions correctly during simultaneous execution by multiple threads', example: 'Use a mutex to make the shared buffer thread-safe.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 137, term: 'Embedded Linux', meaning: 'A version of the Linux kernel adapted and configured for embedded systems with limited resources', example: 'The Raspberry Pi runs Embedded Linux to manage the display and sensors.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 138, term: 'Protocol Stack', meaning: 'A set of layered protocols implementing a network communication standard', example: 'The TCP/IP protocol stack handles all network communication in LwIP.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 139, term: 'Datasheet', meaning: 'Technical document from the manufacturer describing a component\'s specifications, electrical characteristics, and usage', example: 'Consult the STM32 datasheet for GPIO electrical characteristics.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 140, term: 'PWM Duty Cycle', meaning: 'The percentage of time a PWM signal is high within one period, controlling average output power', example: 'A 50% duty cycle on a 5V PWM signal produces an average of 2.5V.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 141, term: 'ICSP', meaning: 'In-Circuit Serial Programming — a method for programming microcontrollers while installed in a circuit', example: 'Use ICSP to flash the bootloader onto the bare AVR chip.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 142, term: 'SWD', meaning: 'Serial Wire Debug — a two-pin ARM debugging interface alternative to JTAG with lower pin count', example: 'Connect ST-Link via SWD to debug the STM32 firmware.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 143, term: 'Z-Wave', meaning: 'A wireless mesh protocol for smart home devices operating in the sub-GHz band for better range', example: 'Z-Wave door sensors report status to the smart home hub.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 144, term: 'TinyML', meaning: 'Running machine learning inference on microcontrollers and edge devices with milliwatts of power', example: 'TinyML on the MCU classifies vibration patterns to detect machine faults.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 145, term: 'RS-485', meaning: 'A balanced differential serial bus standard for multi-point communication over long distances', example: 'RS-485 connects 32 nodes over 1200 meters in an industrial network.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 146, term: 'Current Draw', meaning: 'The amount of electric current consumed by a circuit or component, critical for battery life calculations', example: 'Measure current draw in deep sleep to verify the 10 μA target.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 147, term: 'Pull-up Resistor', meaning: 'A resistor connecting a signal line to a supply voltage, ensuring a defined HIGH state when floating', example: 'I2C lines require pull-up resistors for correct logic levels.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 148, term: 'Debouncing', meaning: 'Filtering out spurious multiple transitions from mechanical switches to register a single clean press', example: 'Software debouncing ignores button state changes within 20 ms.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 149, term: 'Clock Speed', meaning: 'The frequency at which a processor executes instructions, measured in MHz or GHz', example: 'The STM32 runs at up to 168 MHz clock speed.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },
  { id: 150, term: 'Interrupt Priority', meaning: 'A numeric ranking determining which interrupt service routine runs first when multiple interrupts occur simultaneously', example: 'Set emergency shutdown interrupt to highest priority.', category: 'iot', interval: 1, nextReview: now, repetitions: 0, practiceCount: 0 },

]

/** 15 interview questions with model answers */
export const INTERVIEW_QUESTIONS = [
  {
    id: 1,
    question: 'Tell me about yourself.',
    answer: 'I am a software engineer with a passion for embedded systems and IoT development. I have experience working with microcontrollers like STM32 and ESP32, writing firmware in C/C++, and integrating cloud connectivity using MQTT and REST APIs. I enjoy solving complex hardware-software challenges and thrive in cross-functional teams where I can collaborate with both hardware engineers and backend developers.',
    category: 'behavioral',
  },
  {
    id: 2,
    question: 'What are your greatest strengths?',
    answer: 'My greatest strengths are systematic problem-solving and attention to detail, which are critical in embedded development where bugs can be hard to reproduce. I am also a strong communicator — I can translate technical concepts for both engineering teams and non-technical stakeholders. Additionally, I am proactive about learning; when I encounter an unfamiliar protocol like LoRaWAN or Matter, I invest time to understand it deeply before implementing.',
    category: 'behavioral',
  },
  {
    id: 3,
    question: 'What is your greatest weakness?',
    answer: 'I can sometimes over-engineer solutions by considering edge cases that may never occur in practice. I have been working on this by applying the YAGNI principle — building only what is needed now and refactoring when requirements evolve. This has made me faster at delivering initial implementations while keeping code maintainable.',
    category: 'behavioral',
  },
  {
    id: 4,
    question: 'Describe a challenging technical problem you solved.',
    answer: 'On a recent IoT project, our device was intermittently resetting in the field but worked fine on the bench. Through systematic debugging — examining the watchdog reset log, adding more instrumentation, and stress-testing under temperature extremes — I identified a stack overflow in a low-priority RTOS task triggered only under heavy sensor load. I fixed it by increasing the task stack size and adding a stack watermark monitor. The devices have been stable since deployment.',
    category: 'behavioral',
  },
  {
    id: 5,
    question: 'Where do you see yourself in 5 years?',
    answer: 'In five years, I see myself as a senior engineer or technical lead specializing in IoT system architecture. I want to have shipped products that impact thousands of users, deepened my expertise in real-time systems and wireless protocols, and mentored junior engineers. I am also interested in exploring the intersection of ML at the edge and resource-constrained devices.',
    category: 'behavioral',
  },
  {
    id: 6,
    question: 'Why do you want this position?',
    answer: 'This role aligns perfectly with my skills in embedded firmware and IoT connectivity, and I am excited by the opportunity to work on products that directly improve people\'s lives. I am drawn to your company\'s focus on low-power design — it is a technical area I genuinely enjoy. I also appreciate the team\'s culture of engineering excellence and continuous learning evident from your engineering blog.',
    category: 'behavioral',
  },
  {
    id: 7,
    question: 'What is an API and how does it work?',
    answer: 'An API (Application Programming Interface) is a defined contract that allows two software systems to communicate. One system exposes endpoints or functions; the other calls them to request data or trigger actions. For example, a RESTful HTTP API receives requests at a URL like GET /sensors/1, processes the query, and returns a JSON response. The caller does not need to know the internal implementation — just the interface.',
    category: 'technical',
  },
  {
    id: 8,
    question: 'Explain the difference between REST and GraphQL.',
    answer: 'REST uses fixed endpoints (one URL per resource) and the server determines what data is returned. GraphQL uses a single endpoint where the client specifies exactly which fields it needs in the query, preventing over-fetching or under-fetching of data. REST is simpler and cacheable by default; GraphQL is more flexible and reduces network round trips when you need data from multiple related resources. For IoT dashboards with varied data views, GraphQL can be advantageous.',
    category: 'technical',
  },
  {
    id: 9,
    question: 'What is Docker and why would you use it?',
    answer: 'Docker is a containerization platform that packages an application with all its dependencies into a lightweight, portable container. This ensures the application runs identically across development, staging, and production environments. In IoT backends, Docker is valuable for running MQTT brokers, time-series databases, and microservices in isolated containers. It also simplifies CI/CD pipelines since each build produces a deterministic image.',
    category: 'technical',
  },
  {
    id: 10,
    question: 'Explain the difference between I2C and SPI.',
    answer: 'I2C uses two wires (SDA for data, SCL for clock) and supports multiple devices on the same bus using 7-bit addresses. It is slower (up to ~400 kHz standard) but requires fewer pins, making it ideal for sensors. SPI uses four wires (MOSI, MISO, SCK, CS) and is faster (up to tens of MHz) but requires a dedicated chip-select line for each device. Use I2C for low-speed sensors; use SPI for displays, ADCs, or flash memory where throughput matters.',
    category: 'iot',
  },
  {
    id: 11,
    question: 'How do you minimize power consumption in an IoT device?',
    answer: 'I apply several strategies: (1) Use deep sleep between sensor readings — wake on a timer or external interrupt only. (2) Disable unused peripherals and clock domains. (3) Select a low-power MCU rated for sub-microamp sleep current. (4) Minimize radio transmission time — batch data and use efficient protocols like LoRaWAN or BLE. (5) Optimize firmware — avoid busy-waiting, use DMA for transfers. (6) Profile actual current draw with a power monitor like the Nordic PPK2.',
    category: 'iot',
  },
  {
    id: 12,
    question: 'What is MQTT and why is it popular for IoT?',
    answer: 'MQTT (Message Queuing Telemetry Transport) is a lightweight publish-subscribe messaging protocol designed for constrained devices and unreliable networks. Devices publish messages to topics on a broker (e.g., Mosquitto); subscribers receive messages on those topics. It is popular in IoT because it has a minimal header overhead (~2 bytes), supports QoS levels for delivery guarantees, handles intermittent connectivity gracefully with persistent sessions, and scales to millions of connected devices.',
    category: 'iot',
  },
  {
    id: 13,
    question: 'Explain interrupt-driven vs polling approaches.',
    answer: 'Polling means the CPU continuously checks a peripheral status register in a loop, wasting cycles even when no event has occurred. Interrupt-driven means the peripheral signals the CPU only when an event occurs, and the CPU executes an ISR to handle it. Interrupts are more efficient for infrequent events (e.g., button presses, UART receive), while polling can be acceptable for very fast, predictable events where interrupt overhead would dominate. In RTOS systems, interrupts are preferred to keep tasks responsive.',
    category: 'iot',
  },
  {
    id: 14,
    question: 'What is an RTOS and when do you need one?',
    answer: 'An RTOS (Real-Time Operating System) provides deterministic task scheduling with guaranteed response times, unlike general-purpose OSes. It offers preemptive multitasking, inter-task communication (queues, semaphores), and timing services. You need an RTOS when your application has multiple concurrent tasks with different deadlines — for example, a device that simultaneously controls a motor (hard real-time), reads sensors (periodic), and handles Wi-Fi communication (bursty). For simple single-task firmware, a bare-metal super-loop suffices.',
    category: 'iot',
  },
  {
    id: 15,
    question: 'How do you approach debugging a firmware crash?',
    answer: 'First, I capture the fault context — check if a watchdog reset occurred and read the fault status registers (e.g., ARM CFSR, HFSR). I enable HardFault handlers to capture the stack frame and PC at the time of crash. I then use the debugger (GDB/JTAG) to examine the stack and identify the faulting instruction. Common root causes include stack overflow, NULL pointer dereference, unaligned memory access, or corrupted function pointers. I also use stack canaries and enable MPU protection zones to catch issues earlier.',
    category: 'iot',
  },
]
